name: Utils

on:
  pull_request:
    paths:
      - .manala.yaml
      - .github/workflows/_lint.yaml
      - .github/workflows/_test.yaml
      - .github/workflows/utils.yaml
      - utils/**
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Run with tmate debugging
        required: false
        default: false

jobs:
  utils_lint:
    name: Lint
    uses: ./.github/workflows/_lint.yaml
    with:
      debug: ${{ inputs.debug == true }}
      collection: utils
  utils_test:
    name: Test
    uses: ./.github/workflows/_test.yaml
    with:
      debug: ${{ inputs.debug == true }}
      collection: utils
